include: package:lints/recommended.yaml
analyzer:
  exclude:
    - "**\/*.g.dart"
    - "**\/*.freezed.dart"
    - build/**
linter:
  rules:
     avoid_print: true
     prefer_single_quotes: true
     always_declare_return_types: true
     require_trailing_commas: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options